---
name: HTML-Menu-Pages
version: 0.27
author:
  - 'Dirk Lindner <lze@cpan.org>'
abstract: Tool for Building HTML Pages
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  CGI::QuickApp: '>=0.25'
  Module::Build: '>=0.2808'
  Template::Quick: '>=0.25'
  Test::More: '>=0.7'
  Test::Pod: '>=1.26'
  Test::Pod::Coverage: '>=0.55'
provides:
  HTML::Menu::Pages:
    file: lib/HTML/Menu/Pages.pm
    version: 0.27
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
